### ISSUE TITLE
stats.rateLimitErrors array should be generated based on other constants

### ISSUE THREAD

**Issue by mtrunkat** [apify/apify-client-js#110]
See https://github.com/apifytech/apify-client-js/blob/05fb0851b0b33270b403542604b33da7067b9552/src/index.js#L164

Could be generated as n-times zero where `n = Math.max(REQUEST_ENDPOINTS_EXP_BACKOFF_MAX_REPEATS, EXP_BACKOFF_MAX_REPEATS);`

**Comment by mtrunkat** [comment]
Or better just start with an empty array and always push a new item to it

**Comment by mnmkng** [comment]
Done in v1
