### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by rixw** [apify/apify-client-js#118]
I'm struggling to use this library in Typescript, a `.d.ts` file would be brilliant (but sorry, I don't have the chops to do it myself).

**Comment by mnmkng** [comment]
Sorry, we're not familiar with Typescript. But if you know a good resource on making `.d.ts` files, I'd like to read it.

**Comment by rixw** [comment]
Best resource is presumably the official Typescript documentation:
https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by nategraves** [comment]
I took a crack at this using the docs in the repo. There seemed to be a few places where the client docs differ from the API docs, so I'm not sure if this is 100% accurate, but hopefully it's a useful starting point:

https://gist.github.com/nategraves/76f48350a45867c9226c40bbdc623714

**Comment by pocesar** [comment]
thanks for the effort @nategraves it's actually in progress, it's being (slowly) rewritten in TS instead of just providing the types

**Comment by B4nan** [comment]
Closing as v2 is TS rewrite
