### ISSUE TITLE
Missing method for "Run actor synchronously"

### ISSUE THREAD

**Issue by moltar** [apify/apify-client-js#122]
Documented here: https://apify.com/docs/api/v2#/reference/actors/run-actor-synchronously

But there is no corresponding method or option.

**Comment by mnmkng** [comment]
Yes, that seems to be true. You can use the [`Apify.call()`](https://sdk.apify.com/docs/api/apify#apifycallactid-input-options-promise-actorrun-typedefs-actorrun) method of the Apify SDK to do it.

An extra benefit of using `Apify.call()` is that it's not limited by the 300 second max timeout of the API endpoint.

**Comment by mnmkng** [comment]
I kept it to track that we still need to add some methods that will return the output and not the run object.
