### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by jancurn** [apify/apify-client-js#134]
The documentation is in terrible state, it needs to be greatly improved.

Descriptions of functions and params can be taken straight from API docs, plus from
each function, there should be a link to the corresponding API endpoint. Once we have jsdoc for all functions, we need to write a better intro.

**Comment by m-murasovs** [comment]
Notes from the [revamp document](https://www.notion.so/API-Reference-83194d21d122433d988dc69e5896d882): 

**Apify Client TODO:**

- Start with "How to install" and a basic intro

- Lukas: People fighting with the apify-client (I remeber my old days too). Maybe its documentation could mention that for simple use-cases, it's better to use the SDK directly?

- https://app.intercom.io/a/apps/kod1r788/inbox/inbox/1540415/conversations/21983777437

**Comment by mnmkng** [comment]
I think the docs are better now. Open new issues if you think something needs improvements.
