### ISSUE TITLE
Intellisense does not work

### ISSUE THREAD

**Issue by amitpareek** [apify/apify-client-js#142]
Hey Guys,
I have tried v0.6 and v0.10 both, but I dont get the intellisense working for the library. I am using VS Code v1.47.3.

Any idea, on how can I get it working.

The client property on Apify SDK also points to apify-client library, and hence even that is not working.

**Comment by mnmkng** [comment]
Works fine for me in WebStorm since the v1.0.0 release. The problem in the SDK is of a different nature and we'll fix it there.
![image](https://user-images.githubusercontent.com/23726914/105744671-bc327800-5f3d-11eb-8d2f-bfa3c2b9e333.png)
