### ISSUE TITLE
Add status parameter to list actor (task) runs method

### ISSUE THREAD

**Issue by mtrunkat** [apify/apify-client-js#143]
@mnmkng this parameter will be added soon to the API, let's include it in the new client.

`/v2/acts/${ACTOR_ID}/runs?token=${TOKEN}&status=${ACT_JOB_STATUSES.SUCCEEDED}`

**Comment by mnmkng** [comment]
Done https://github.com/apify/apify-client-js/commit/77f30945397d938734d61427247d676a88a64e5b
