### ISSUE TITLE
Add methods for runs and builds list for a user

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-client-js#152]
The endpoints for all user builds and runs are ready. We need to address them into client see docs:
https://docs.apify.com/api/v2#/reference/actor-runs/run-collection/get-user-runs-list
and
https://docs.apify.com/api/v2#/reference/actor-builds/build-collection/get-user-builds-list

+ update integration tests to use client!

**Comment by fnesveda** [comment]
This looks like it's done
