### ISSUE TITLE
Add opt out option for non-gzipped put record into kv store

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-client-js#153]
Regarding changes in https://github.com/apify/apify-core/pull/998, we need to make gziping of payload uploaded into kv store opt-out. It means we want to gzips payload as now but we need to add an option for disabling it.

Context:
After removing signed URLs upload we decided to keep content-encoding setting up to the user(we store data in the format as he put them). It means if the user uploads gzipped files, he needs to ungzips them(the most HTTP client do it by default). But there can be a case where the user wants to have data stored in kv store in raw format to be able to download them without unzipping.

**Comment by mtrunkat** [comment]
@mnmkng we now decompress record of any size when reading from a key-value store so probably there is no point in adding this opt-out from compression on put request.

**Comment by mnmkng** [comment]
@mtrunkat I'm not sure I understand. Decompression is normally done client-side. What does "we now decompress" mean?
