### ISSUE TITLE
Expose axios `httpAgent` and `httpsAgent`

### ISSUE THREAD

**Issue by nchase** [apify/apify-client-js#177]
It looks like this library uses axios under the hood. 

Is it possible to expose the `httpAgent` and `httpsAgent` properties (their definition in axios is [here](https://github.com/axios/axios/blob/master/README.md#request-config)) in the ApifyClient constructor?

We need to use non-standard `httpAgent` and `httpsAgents` and we'd like to use those with this library, so that we can take advantage of the automatic retries and exponential backoff.

If this isn't possible with the current architecture, can you suggest another way to use a custom `httpAgent`/`httpsAgent`?

**Comment by mnmkng** [comment]
I think we could do that. Or maybe the existing transform request function option could be used for it. (It's undocumented and used for our internal purposes) 

Out of curiosity, why do you need custom agents?

**Comment by nchase** [comment]
> Out of curiosity, why do you need custom agents?

We use a custom http agent that acts as a proxy and prevents sensitive user data from being passed over our servers or Apify’s servers.

**Comment by mnmkng** [comment]
Ah, got it, thanks. Please let me know if the `options.requestInterceptors` works for you. Something like this should work:

```js
const client = new ApifyClient({
    token: 'TOKEN',
    requestInterceptors: [
        (config) => {
            config.httpsAgent = myCustomAgent;
            return config;
        }
    ]
})
```

**Comment by nchase** [comment]
Thanks @mnmkng! We'll try this soon.

**Comment by nchase** [comment]
Upon closer inspection, I found some bugs in our attempts at handling this. I'm going to close this until it's entirely clear what's going on.

Thanks for your help @mnmkng!
