### ISSUE TITLE
API calls quite often get stuck

### ISSUE THREAD

**Issue by mnmkng** [apify/apify-client-js#225]
While debugging issues in the SDK we found that the client requests quite often get stuck for minutes without any reason. The maximum time it should take to run all exponential backoff retries is around two and a half minutes, but the requests would often get stuck for 4 - 6 minutes. This happened multiple times over the course of a one hour test.

```
2022-01-27T15:58:37.150Z Updating request EAaArVRs5qV39C9
2022-01-27T16:04:08.019Z Request updated
```

To isolate the problem I ran the same test using plain `axios` and it never got stuck.

Now, the test with `axios` was extremely simple and I did not try to replicate all the options we use in the client, so this does not prove that the bug is somewhere in the client code. It might as well be a bug of some `axios` configuration. Or a bug of our API that behaves differently when certain parameters are sent - e.g. in `axios` I used `token` in params, not in header and I never used the `clientKey` param.

We should fix this. There's a high chance it's related to the 0 concurrency bug of actors.

**Comment by B4nan** [comment]
IIRC this was invalid in the end, right?

**Comment by mnmkng** [comment]
Yeah, I think it was some weird combination of timeouts, but I don't really remember TBH.
