### ISSUE TITLE
Typings for 2.1.0. are off

### ISSUE THREAD

**Issue by mhamas** [apify/apify-client-js#229]
When trying 
```
await this.apifyClient!
    .tasks()
    .create({
        actorId,
        name: taskName,
        options: { build: buildNumber, timeout: TASK_TIMEOUT_SECONDS },
    }); 
```
I run into the following issues
- `actorId` is not present in typings and it seems that the client actually expects `actId`
- `timeout` is present in typings but the runtime complains. it seems the legacy `timeoutSecs` works

**Comment by vladfrangu** [comment]
Looking at the code, seems like the only properties that cannot be changed are `userId`, `stats` and the `*At` fields. If that's correct I'll update the types accordingly.

For the `timeout` vs `timeoutSecs`, from what I see TaskOptions has only `timeoutSecs` defined. 👀 Is timeoutSecs deprecated? If so, I can update it 👍

**Comment by mhamas** [comment]
Hm...looking at the API probably not and it should e still `timeoutSecs`. But I believe the type hints in IDE were showing me `timeout` instead.

**Comment by vladfrangu** [comment]
> But I believe the type hints in IDE were showing me `timeout` instead

What version of the client are you on? It looks fine on 2.1.0 too 👀 
![image](https://user-images.githubusercontent.com/17960496/153392887-4dd1ef43-664e-4beb-9251-9e6b81cef49d.png)

**Comment by mhamas** [comment]
Ok, this is probably my bad. Checking it now and it does show `timeoutSecs`.

**Comment by vladfrangu** [comment]
I'm gonna close this for cleanup sake, please re-open or followup if this is still an issue 🙏
