### ISSUE TITLE
Is generic type for dataset rightly typed?

### ISSUE THREAD

**Issue by JJetmar** [apify/apify-client-js#267]
I recently run into [apify_client#L140](https://github.com/apify/apify-client-js/blob/8f7eeed5626e9de4c38bd3baa495c700ff5e2503/src/apify_client.ts#L140) and I am not sure if the `Data` generic type is rightly typed here. 

```typescript
dataset<Data extends Record<string | number, unknown> ...
```
This disallows me to use my own interface type definition for example [(sandbox):](https://www.typescriptlang.org/play?#code/MYGwhgzhAEpgXvAPAETAFzNApgD3dgHYAmMAStsAPYBOxSE6NAloQObQA+0hArgLYAjbDQA00XoQDWhKgHdCAPkXQA3tAC+AKC2sCNAGZhg2aAAUaVYr2Do1W6I+iRWALmiMW7ANwOnVAwMRd09WNl9tLUJsOVhwRCQLKxt0RW8gA)
```
interface Product {
    asin: string;
    offer: string;
}
```
It would be nice to be able to set/get specific typescript interface for better type safety.

My current approach:
```
(((await Actor.apifyClient.dataset(datasetId).listItems()).items as unknown) as Product[])
```
Since the loaded data are right I think the only problem is only in the required type definition.

**Comment by B4nan** [comment]
What error do you get it you put the interface there?

**Comment by B4nan** [comment]
Changing the signature to use `any` instead of `unknown` helps, I guess let's do that.

```ts
dataset<Data extends Record<string, any> = Record<string, any>>(id: string): DatasetClient<Data>;
```
