### ISSUE TITLE
Actor.getInput() returns null

### ISSUE THREAD

**Issue by gustavotr** [apify/apify-client-js#270]
Using v3, if you create a new actor using `apify create` and choose Puppeteer or Platwright crawller, when running the code an error is thrown trying to read input variable.
![Screenshot_20220820_174922](https://user-images.githubusercontent.com/5346766/185752474-6f47bf90-0119-46d7-bf53-ffcc752769c1.png)

**Comment by mnmkng** [comment]
We'll be releasing new version of CLI with new templates soon. It should fix this.
