### ISSUE TITLE
actor/task .call are missing waitSecs option

### ISSUE THREAD

**Issue by metalwarrior665** [apify/apify-client-js#282]
The type ActorStartOptions has `waitForFinish` but `actor('actor').call` (and task) where it is used should have `waitSecs` instead. I would do a PR but not sure how you want to structure the types

**Comment by vladfrangu** [comment]
Out of curiosity, why is that? The api expects waitForFinish, not waitSecs. Is this just a rename in the client for clarity sake or is it something else?

**Comment by metalwarrior665** [comment]
@vladfrangu I think this was designed by @mnmkng but as I understand it: The `.start()` is basically the normal client run so it passes all the params to the API (`waitForFinish` is API param). But `.call()` is a wrapper of `.start()` that waits for the run to finish fully. This is feature of the client, not supported but the API so the `waitSecs` is option only to the client, not API. 

I agree that it is a bit confusing since vast majority of the client just reflects the API but we generally agreed that the client should have utility logic on top of it.

**Comment by vladfrangu** [comment]
Oh crap, I think I see what you're saying. `.call` re-uses the type for `.start` but in the case of `waitSecs` vs `waitForFinish`, `.call` expects the former, and `.start` the latter. I'll fix this, thx
