### ISSUE TITLE
Add endpoints for user limits and usage

### ISSUE THREAD

**Issue by m-murasovs** [apify/apify-client-js#329]
These are currently missing, so on Console, we have to make regular API calls without the client. It would be better to use the client.

**Comment by gippy** [comment]
We also need to add documentation for multifile select, just so that I do not forget.

**Comment by gippy** [comment]
I'm assigning this to you @MFori even though you know nothing about it, just so that you can learn how to write docs.
Please ask me about this before you start. I will explain it to you.

**Comment by MFori** [comment]
Reopening as it's not completed at all
