### ISSUE TITLE
Pass AWSALB cookie so that API requests go to the same server

### ISSUE THREAD

**Issue by jancurn** [apify/apify-client-js#46]
This will enable us to use cache and improve performance.

**Comment by mtrunkat** [comment]
Don't forgot to also setup HAProxy sticky session cookies https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/

**Comment by mtrunkat** [comment]
There is no point in doing this ATM as:
- We have no caching that could benefit from this
- It could easily overloaded the pod

Closing.
