### ISSUE TITLE
`ActorCollectionCreateOptions` type is incomplete

### ISSUE THREAD

**Issue by jirimoravcik** [apify/apify-client-js#479]
The interface `ActorCollectionCreateOptions` https://github.com/apify/apify-client-js/blob/master/src/resource_clients/actor_collection.ts#L60 is incomplete. API also allows passing `defaultRunOptions` (build, timeout and so on), which the interface does not have.

**Comment by B4nan** [comment]
sidenote: I'd really appreciate if issues like this are resolved by some other team than us, as we don't have the insight on what the API is actually capable (outside of what is documented), or at least someone provides info on what should be there.

**Comment by jirimoravcik** [comment]
> sidenote: I'd really appreciate if issues like this are resolved by some other team than us, as we don't have the insight on what the API is actually capable (outside of what is documented), or at least someone provides info on what should be there.

The ultimate end-goal is to have a single typings package that would be used in client/sdk and all platform repos. But we're not there yet.

**Comment by drobnikj** [comment]
Let's fix this type for now and create new issue in core to share types with API codebase.
