### ISSUE TITLE
Rename "acts" namespace to "actors"

### ISSUE THREAD

**Issue by jancurn** [apify/apify-client-js#76]
But keep "acts" for backwards compatibility. Add unit test for this.

**Comment by jancurn** [comment]
And perhaps also add a deprecation warning to old "acts" functions, e.g. using some function decorator.

**Comment by mtrunkat** [comment]
We should also rename method names runAct => runActor and param names actId to actorId, ...

**Comment by mnmkng** [comment]
I've already done this in my API split endeavor.

**Comment by jancurn** [comment]
I’d be careful and avoid mixing code refactoring with changes. Makes
debugging easier.

**Comment by mnmkng** [comment]
Done in v1
