### ISSUE TITLE
Documentation is missing definition of returned objects

### ISSUE THREAD

**Issue by gippy** [apify/apify-client-js#78]
The generated documentation shows correctly return types of each function, but the return types are not defined anywhere so they do not show up in the documentation and thanks to it it's impossible to know what each function returns.

**Comment by mtrunkat** [comment]
We should extract this info from API Blueprint documentation (Apiary). Code converting API Blueprint type definitions to JS schema and objects is used in integration tests.

**Comment by mtrunkat** [comment]
Or we could just link API, the only problem there is that it's wrapped under the data property:

```json
{
   "data": [The value returned by client]
}
```

**Comment by mtrunkat** [comment]
Let's just link each object to API docs.

**Comment by mnmkng** [comment]
The information that the response object does not contain the `data` property needs to be written somewhere in **BOLD CAPS**, because I always check the API docs to see what the response looks like and it never works. 👎

**Comment by mnmkng** [comment]
We only link to the API docs now.
